"""Domain ports."""

from __future__ import annotations

from typing import Protocol

from ticket_processor.domain.models import (
    Attachment,
    EmailMessage,
    Product,
    ProductCategoryLevel1,
    ProductCategoryLevel2,
    Purchase,
)


class EmailPort(Protocol):
    def search_candidate_emails(self, query: str) -> list[EmailMessage]: ...
    def get_email(self, message_id: str) -> EmailMessage: ...
    def download_attachment(self, message_id: str, attachment: Attachment) -> bytes: ...
    def reply_to_email(self, email: EmailMessage, body: str) -> None: ...
    def mark_as_processed(self, message_id: str, label_name: str) -> None: ...


class AttachmentTextExtractorPort(Protocol):
    def supports(self, attachment: Attachment) -> bool: ...
    def extract_text(self, content: bytes, attachment: Attachment) -> str: ...


class ReceiptItemsExtractorPort(Protocol):
    def extract_products(self, receipt_text: str, attachment_name: str) -> list[Product]: ...


class ClassifierPort(Protocol):
    def classify(
        self,
        product_name: str,
    ) -> tuple[ProductCategoryLevel1, ProductCategoryLevel2]: ...


class SheetsPort(Protocol):
    def purchase_exists(self, purchase_id: str) -> bool: ...
    def append_purchase(self, purchase: Purchase) -> None: ...


class SupabasePort(Protocol):
    def purchase_exists(self, purchase_id: str) -> bool: ...
    def upsert_purchase(self, purchase: Purchase) -> None: ...


class LlmPort(Protocol):
    def complete(self, prompt: str, system_prompt: str | None = None) -> str: ...


class LoggerPort(Protocol):
    def debug(self, message: str, **kwargs: object) -> None: ...
    def info(self, message: str, **kwargs: object) -> None: ...
    def warning(self, message: str, **kwargs: object) -> None: ...
    def error(self, message: str, **kwargs: object) -> None: ...
    def exception(self, message: str, **kwargs: object) -> None: ...
    def bind(self, **kwargs: object) -> LoggerPort: ...
